name: Pull Request Validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validation:
    name: Code Validation
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Type checking
        run: npx tsc --noEmit
        
      - name: Lint check
        run: npm run lint
        
      - name: Format check
        run: npm run format:check
        
      - name: Build project
        run: npm run build
        
      - name: Start dev server and run E2E tests
        run: npm run test